import type { User, Trip, ActivityBlock, CheckIn, ActivitySuggestion } from '../types';

export const MOCK_USER: User = {
  id: 'user-001',
  email: 'alex@roamio.app',
  display_name: 'Alex',
  created_at: '2024-01-15T08:00:00Z',
};

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-banff-001',
    user_id: 'user-001',
    destination: 'Banff, Alberta',
    start_date: '2026-03-14',
    end_date: '2026-03-16',
    created_at: '2026-03-01T10:00:00Z',
    destination_image: 'https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=800',
  },
  {
    id: 'trip-kyoto-002',
    user_id: 'user-001',
    destination: 'Kyoto, Japan',
    start_date: '2026-04-05',
    end_date: '2026-04-10',
    created_at: '2026-03-05T14:30:00Z',
    destination_image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
  },
];

export const MOCK_ACTIVITY_BLOCKS: Record<string, ActivityBlock[]> = {
  'trip-banff-001': [
    // Day 1
    {
      id: 'block-001',
      trip_id: 'trip-banff-001',
      day_index: 0,
      place_name: 'Banff Upper Hot Springs',
      resolved_place_id: 'ChIJbf6ABCD1234',
      resolved_place_name: 'Banff Upper Hot Springs',
      resolved_lat: 51.1574,
      resolved_lng: -115.5554,
      activity_type: 'spa',
      energy_cost_estimate: 2,
      start_time: '09:00',
      end_time: '11:00',
    },
    {
      id: 'block-002',
      trip_id: 'trip-banff-001',
      day_index: 0,
      place_name: 'Whyte Museum of the Canadian Rockies',
      resolved_place_id: 'ChIJwhyte5678',
      resolved_place_name: 'Whyte Museum of the Canadian Rockies',
      resolved_lat: 51.1766,
      resolved_lng: -115.5698,
      activity_type: 'museum',
      energy_cost_estimate: 3,
      start_time: '12:00',
      end_time: '14:00',
    },
    {
      id: 'block-003',
      trip_id: 'trip-banff-001',
      day_index: 0,
      place_name: 'Johnston Canyon Trail',
      resolved_place_id: 'ChIJjohnston9012',
      resolved_place_name: 'Johnston Canyon',
      resolved_lat: 51.2436,
      resolved_lng: -115.8346,
      activity_type: 'hiking',
      energy_cost_estimate: 7,
      start_time: '15:30',
      end_time: '18:00',
    },
    // Day 2
    {
      id: 'block-004',
      trip_id: 'trip-banff-001',
      day_index: 1,
      place_name: 'Lake Louise Shoreline Hike',
      resolved_place_id: 'ChIJlakelouise3456',
      resolved_place_name: 'Lake Louise',
      resolved_lat: 51.4254,
      resolved_lng: -116.1773,
      activity_type: 'hiking',
      energy_cost_estimate: 8,
      start_time: '08:00',
      end_time: '12:00',
    },
    {
      id: 'block-005',
      trip_id: 'trip-banff-001',
      day_index: 1,
      place_name: 'Post Hotel Dining Room',
      resolved_place_id: 'ChIJposthotel7890',
      resolved_place_name: 'The Post Hotel & Spa',
      resolved_lat: 51.4236,
      resolved_lng: -116.1756,
      activity_type: 'restaurant',
      energy_cost_estimate: 2,
      start_time: '13:00',
      end_time: '14:30',
    },
    {
      id: 'block-006',
      trip_id: 'trip-banff-001',
      day_index: 1,
      place_name: 'Moraine Lake Viewpoint',
      resolved_place_id: 'ChIJmoraine1234',
      resolved_place_name: 'Moraine Lake',
      resolved_lat: 51.3217,
      resolved_lng: -116.1860,
      activity_type: 'landmark',
      energy_cost_estimate: 4,
      start_time: '15:30',
      end_time: '17:30',
    },
    // Day 3
    {
      id: 'block-007',
      trip_id: 'trip-banff-001',
      day_index: 2,
      place_name: 'Banff Farmers Market',
      resolved_place_id: 'ChIJmarket5678',
      resolved_place_name: 'Banff Farmers Market',
      resolved_lat: 51.1784,
      resolved_lng: -115.5708,
      activity_type: 'market',
      energy_cost_estimate: 2,
      start_time: '09:00',
      end_time: '10:30',
    },
    {
      id: 'block-008',
      trip_id: 'trip-banff-001',
      day_index: 2,
      place_name: 'Sulphur Mountain Gondola',
      resolved_place_id: 'ChIJgondola9012',
      resolved_place_name: 'Sulphur Mountain',
      resolved_lat: 51.1471,
      resolved_lng: -115.5584,
      activity_type: 'landmark',
      energy_cost_estimate: 5,
      start_time: '11:30',
      end_time: '14:00',
    },
    {
      id: 'block-009',
      trip_id: 'trip-banff-001',
      day_index: 2,
      place_name: 'Vermilion Lakes Sunset Walk',
      resolved_place_id: 'ChIJvermilion3456',
      resolved_place_name: 'Vermilion Lakes',
      resolved_lat: 51.1842,
      resolved_lng: -115.6159,
      activity_type: 'walking',
      energy_cost_estimate: 3,
      start_time: '17:00',
      end_time: '19:00',
    },
  ],
  'trip-kyoto-002': [
    {
      id: 'block-kyoto-001',
      trip_id: 'trip-kyoto-002',
      day_index: 0,
      place_name: 'Fushimi Inari Taisha',
      resolved_place_id: 'ChIJfushimi001',
      resolved_place_name: 'Fushimi Inari-taisha',
      resolved_lat: 34.9671,
      resolved_lng: 135.7727,
      activity_type: 'landmark',
      energy_cost_estimate: 6,
      start_time: '08:00',
      end_time: '11:00',
    },
    {
      id: 'block-kyoto-002',
      trip_id: 'trip-kyoto-002',
      day_index: 0,
      place_name: 'Nishiki Market',
      resolved_place_id: 'ChIJnishiki002',
      resolved_place_name: "Nishiki Market",
      resolved_lat: 35.0050,
      resolved_lng: 135.7650,
      activity_type: 'market',
      energy_cost_estimate: 3,
      start_time: '12:30',
      end_time: '14:30',
    },
  ],
};

export const MOCK_CHECKINS: CheckIn[] = [
  {
    id: 'checkin-001',
    activity_block_id: 'block-001',
    user_id: 'user-001',
    energy_level: 8,
    current_lat: 51.1574,
    current_lng: -115.5554,
    agent_outcome: 'affirmed',
    selected_place_id: null,
    selected_place_name: null,
    timestamp: '2026-03-14T09:05:00Z',
  },
  {
    id: 'checkin-002',
    activity_block_id: 'block-002',
    user_id: 'user-001',
    energy_level: 4,
    current_lat: 51.1766,
    current_lng: -115.5698,
    agent_outcome: 'rerouted',
    selected_place_id: 'ChIJcafe-cozy',
    selected_place_name: 'Bear Street Tavern',
    timestamp: '2026-03-14T12:08:00Z',
  },
];

export const MOCK_SUGGESTIONS: ActivitySuggestion[] = [
  {
    place_id: 'ChIJcozy-cafe-001',
    place_name: 'Whitebark Cafe',
    address: '401 Banff Ave, Banff, AB',
    maps_url: 'https://maps.google.com/?q=Whitebark+Cafe+Banff',
    energy_cost_label: 'very low',
    why_it_fits: 'A cozy mountain cafe perfect for resting your legs with outstanding Rocky Mountain views.',
    distance_km: 0.8,
    estimated_duration_minutes: 45,
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
  },
  {
    place_id: 'ChIJpark-central-002',
    place_name: 'Central Park Banff',
    address: 'Banff Ave & Wolf St, Banff, AB',
    maps_url: 'https://maps.google.com/?q=Central+Park+Banff',
    energy_cost_label: 'very low',
    why_it_fits: 'A quiet green space by the Bow River where you can sit, breathe, and recharge naturally.',
    distance_km: 0.4,
    estimated_duration_minutes: 30,
    image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
  },
  {
    place_id: 'ChIJgallery-003',
    place_name: 'Banff Centre Art Gallery',
    address: '107 Tunnel Mountain Dr, Banff, AB',
    maps_url: 'https://maps.google.com/?q=Banff+Centre+Art+Gallery',
    energy_cost_label: 'low',
    why_it_fits: 'Explore world-class contemporary art at your own leisurely pace in a serene indoor setting.',
    distance_km: 1.2,
    estimated_duration_minutes: 60,
    image_url: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=800',
  },
  {
    place_id: 'ChIJlibrary-004',
    place_name: 'Banff Public Library',
    address: '101 Bear St, Banff, AB',
    maps_url: 'https://maps.google.com/?q=Banff+Public+Library',
    energy_cost_label: 'very low',
    why_it_fits: 'Curl up with a local history book in this peaceful library — ideal for a low-energy afternoon reset.',
    distance_km: 0.3,
    estimated_duration_minutes: 60,
    image_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800',
  },
];